version: 2

sources:
  - name: thelook_ecommerce
    database: bigquery-public-data  
    schema: thelook_ecommerce  
    tables:
      - name: users
      - name: orders
      - name: order_items
      - name: products